# This is a Docker Compose file for deploying this project.
version: '3.7'

services:
  quipu:
    build:
      context: .
      dockerfile: quipu.dockerfile
    tty: true
    labels:
      author: Wildboar Software
      app: quipu
      version: "8.1"
    ports:
      - '17003:17003/tcp'
    volumes:
      - type: bind
        source: ./docker/db
        target: /usr/local/etc/isode/quipu-db
        read_only: false
      - type: bind
        source: ./docker/quiputailor
        target: /usr/local/etc/isode/quiputailor
        read_only: true
      - type: bind
        source: ./docker/isotailor
        target: /usr/local/etc/isode/isotailor
        read_only: true
      # - type: bind
      #   source: ./docker/oidtable.gen.local
      #   target: /usr/local/etc/isode/oidtable.gen.local
      #   read_only: true
      # - type: bind
      #   source: ./docker/oidtable.at.local
      #   target: /usr/local/etc/isode/oidtable.at.local
      #   read_only: true
      # - type: bind
      #   source: ./docker/oidtable.oc.local
      #   target: /usr/local/etc/isode/oidtable.oc.local
      #   read_only: true