##########################################################################
#   Instructions to Make, for PostScript documentation library
##########################################################################




all:;

inst-all:;

install:	inst-all clean

uninstall:;

lint:;

clean:;		rm -f _* *.ps

grind:;

imp:;

preview:;

ps:;
