###############################################################################
#   Instructions to Make, for compilation of ISODE documentation tree
###############################################################################

all clean install inst-all lint:;
