apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quipu-dsa.fullname" . }}
  labels:
    {{- include "quipu-dsa.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quipu-dsa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quipu-dsa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          # Quipu needs these to run.
          stdin: true
          tty: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: itot
              containerPort: 17003
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.edbDataPVCName }}
            - name: data
              mountPath: /var/db/
            {{- end }}
            - name: config
              mountPath: /usr/local/etc/isode/
            {{- if .Values.edbInitConfigName }}
            - name: edb-init
              mountPath:  /usr/local/etc/isode-init/
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.edbDataPVCName }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.edbDataPVCName }}
        {{- end }}
        - name: config
          configMap:
            name: {{ .Values.configName | default (include "quipu-dsa.fullname" .) }}
        {{- if .Values.edbInitConfigName }}
        - name: edb-init
          configMap:
            name: {{ .Values.edbInitConfigName }}
        {{- end }}
