apiVersion: v1
kind: Service
metadata:
  name: {{ include "quipu-dsa.fullname" . }}
  labels:
    {{- include "quipu-dsa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 17003
      protocol: TCP
      name: itot
  selector:
    {{- include "quipu-dsa.selectorLabels" . | nindent 4 }}
