.TH FTAMUSERS 5 "16 Nov 1988"
.\" 
.\"
.\"
.\" 
.\"
.\"
.\"
.\" 
.SH NAME
ftamusers \- list of users prohibited by ftam
.SH SYNOPSIS
.B \*(EDftamusers
.SH DESCRIPTION
The \fIftamusers\fR file contains a list of users who cannot access
this system using the  \fIftam\fR\0(1c) program.
This file contains one user name per line.
.SH "SEE ALSO"
ftam(1C), ftamd(8C)
