#################################################################
#                                                               #
#  ISODECL - HULA project for connectionless ISODE              #
#                                             			#
#  module:  	Makeisodecl - Makefile for ISODECL              #
#  author:   	Bill Haggerty                                   #
#  date:     	4/89                                            #
#                                                               #
#  This makes ISODECL.					 	#
#								#
#################################################################



DIRS	=	tusap susap pusap2 acusap rousap

all clean:;	@for i in $(DIRS); \
		    do (echo "cd $$i; $(MAKE) $@"; \
			      cd $$i; $(MAKE) $@); \
		    done


lint:;

inst-all:;

install:;

grind:;
